name: Test Validation on Multiple OS

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      # 1. Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Установка CMake (если требуется)
      - name: Install CMake (Windows only)
        if: runner.os == 'Windows'
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

      # 3. Сборка проекта
      - name: Build project
        run: |
          mkdir build
          cmake -S . -B build
          cmake --build build

      # 4. Запуск тестов
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
