name: Test Validation on Multiple OS

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (Linux & macOS)
        if: runner.os != 'Windows'
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            sudo apt update
            sudo apt install -y build-essential cmake libgtest-dev
            cd /usr/src/gtest
            sudo cmake .
            sudo make
            sudo mv libgtest*.a /usr/lib/
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            brew update
            brew install cmake googletest
          fi

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          choco install mingw -y
          git clone https://github.com/google/googletest.git
          cd googletest
          cmake -S . -B build -DCMAKE_INSTALL_PREFIX="C:/gtest"
          cmake --build build --target install
          set PATH=%PATH%;C:/gtest/bin

      - name: Build project
        run: |
          mkdir build
          cmake -DCMAKE_BUILD_TYPE=Release -S . -B build
          cmake --build build

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
